### ISSUE TITLE
Missing documentation or readme inside deno.land

### ISSUE THREAD

**Issue by dareksob** [guildenstern70/DyeLog#1]
Please publish your readme to deno.land, will be helpful.

**Comment by guildenstern70** [comment]
Darius, it appears that it's not possible to change a listing on deno.land. The only option I see is to delete DyeLog and register it again with a different path on GitHub, but I would prefer to leave things as they are for compatibility reasons.

If you have suggestions, they are welcome.

**Comment by dareksob** [comment]
Hi, that true, don't break the structure. What if you move the readme to src folder and make a short readme with an internal link to your deno readme. Otherwise all deno.land users see a blank project without any information, that's also bad.

Maybe you can use an deployment script to copy the root readme to src folder.

**Comment by guildenstern70** [comment]
Done. Closing.
